### ISSUE TITLE
Origin https://rohitkaushal7.github.io is not allowed by Access-Control-Allow-Origin.    

### ISSUE THREAD

**Issue by spiderxm** [RohitKaushal7/cf#1]
Origin https://rohitkaushal7.github.io is not allowed by Access-Control-Allow-Origin.

Giving this on submitting our handle

**Comment by RohitKaushal7** [comment]
It works on my computer, mobile, and different browsers (chrome, firefox).. may be try again by reloading the page or using a different browser.

use [this](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) extension if problem persists.
